[package]
name = "dvcli"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/gdcc/rust-dataverse"
license = "MIT"
authors = ["Jan Range <jan.range@simtech.uni-stuttgart.de>"]
description = "Rust library for interacting with the Dataverse API."
documentation = "https://guides.dataverse.org/en/latest/"

[lib]
name = "dataverse"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo"] }
colored = "3.0.0"
exitcode = "1.1.2"
reqwest = { version = "0.12.4", features = [
    "blocking",
    "json",
    "multipart",
    "stream",
] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
typify = "0.4.3"
colored_json = "5.0.0"
atty = "0.2.14"
indicatif = "0.18.0"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = "0.7.11"
bytes = "1.6.0"
futures = "0.3.30"
md5 = "0.8.0"
tokio-stream = "0.1.16"
async_zip = { version = "0.0.18", features = ["tokio", "deflate"] }
walkdir = "2.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
keyring = { version = "3.6.1", features = [
    "apple-native",
    "windows-native",
    "sync-secret-service",
] }
url = "2.5.4"
uuid = "1.12.0"
sha2 = "0.10.8"
sha1 = "0.10.6"
variantly = "0.4.0"
lazy_static = "1.4.0"
sqlx = { version = "0.8.4", features = ["runtime-tokio-native-tls", "sqlite"] }
dirs = "6.0.0"
mime_guess = "2.0.5"
infer = "0.19.0"
bon = "3.6.3"
rpassword = "7.3.1"
dialoguer = "0.12.0"
regress = "0.10.4"

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
libdbus-sys = { version = "0.2.5", features = ["vendored"] }

[[bin]]
name = "dvcli"
path = "src/bin/cli.rs"

[dev-dependencies]
httpmock = "0.8.1"
rand = "0.9.0-alpha.1"
tempfile = "3.19.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
